---
title: "Data Visualization topics"
author: Natalie Boychuk 
date: October 2020 
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```


```{r creating a dataframe}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

##Scatterplots! 

Create my first scatterplot ever. 

```{r}
ggplot(weather_df, aes(x= tmin, y = tmax)) +
    geom_point()
```

New approach, same plot 
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Save and edit a plot object 
Jeff uses this less frequently but it's helpful that you can save that as a name 
```{r}
weather_plot = 
    weather_df %>% 
    ggplot(aes(x = tmin, y = tmax))
```


## Advanced scatterplot 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
```

## Part II: Data Visualization 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5)
```

## Labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs (
    title = "Temperature Plot",
    x = "Minimum Daily Temperature (C)",
    y = "Maximum Daily Temperature (C)",
    caption = "data from rnooaa package: temperatures in 2017"
  ) 
```

